spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/bcm
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
#        format_sql: true
        #Querydsl이 그려주는 JPQL보기
#        use_sql_comments: true
  devtools:
    restart:
      enabled: true
#    livereload:
#      enabled: true
  thymeleaf:
    cache: false
    #SpringSecurity
  security:
    user:
      name: user
      password: 1234
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace



#커스텀
custom:
  negativeDepositLimit: 3000

#p6spy
decorator:
  datasource:
    p6spy:
      ##운영환경에서는 false로 변경, 리소스 소모
      enable-logging: true


#세션 설정
server:
  servlet:
    session:
#      document.cookie와 같은 자바스크립트로 쿠키를 조회하는 것을 막는 옵션
#      브라우저에서 HTTP Only가 설정된 쿠키를 조회할 수 없다.
#      서버로 HTTP Request 요청을 보낼때만 쿠키를 전송한다.
#      이를 통해 XSS(Cross Site Scripting) 공격을 차단할 수 있다.
      timeout: 60m
      http-only: true
      cookie:
        max-age: 60m


