spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/bcm
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        #Querydsl이 그려주는 JPQL보기
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
